### ISSUE TITLE
Mail can't be sent

### ISSUE THREAD

**Issue by JayMan1** [ChildrenOfUr/cou-issues#1852] opened 2016-09-28 04:46 UTC
Every time I attempt to send a message through the mailbox, the client freezes up, then unfreezes and looks like a server reset in the global chat.  I have to reload and still can't send the mail.

**Comment by RobertBlackhart** [comment] 2016-10-07 18:46
@JayMan1 Is this still reproducible for you? Is this on dev or live?

It looks like 'Zad was successful in global chat just now in sending mail:

```
'Zad The Destroyer BOT [2:38 PM]  
I do, let me find a mail box.  :)

Kshandra BOT [2:39 PM]  
fabulous, thanks.

'Zad The Destroyer BOT [2:39 PM]  
Ok, I just sent some.
```

```
userdata=> select id from messages where to_user = 'Kshandra' and from_user = $$'Zad The Destroyer$$;
  id
------
 2528
(1 row)
```

**Comment by JayMan1** [comment] 2016-10-10 03:34
Oh it's on live. It seems to be working for me at the moment though. I just sent three messages and all of them sent correctly. First time in awhile it has worked for me.

**Comment by RobertBlackhart** [comment] 2016-10-10 03:35
Fell free to reopen this issue if you notice problems in the future. Since it seems to be working now, I'm going to close it for now.

**Closed as completed by RobertBlackhart** 2016-10-10 03:35 UTC
Labels: bug, awaiting response
