### ISSUE TITLE
Badge data not saving correctly sometimes

### ISSUE THREAD

**Issue by babi1** [ChildrenOfUr/cou-issues#471] opened 2016-02-24 07:29 UTC
I have few issues:

**Giants**:
-  Pot Emblem, each time I got one in my bag  I am able to iconize an Icon of Pot.
-  When I have all Emblems in my bag I dont get the Super-Sized Sycophant

**Cooking**:
- First Blender, Saucepan  and Grill achievements dont come up, I have used them more than 11 times

**Trees**:
- I havent got any even if I am sure I have petted, watered and harvested more than the 1st badges :D 
- _side note _ :  I have a huuuuuuge quantity of spices, last time I have checked threre were more than 400 that I have never harvested. I should have a less quatity for sure
  a part all that is really pure fun.

**Comment by RobertBlackhart** [comment] 2016-03-02 23:20
Pot emblem problem resolved in #484 (I believe)
Sycophant achievement is not currently tracked (not a bug)
Spices count is probably related to #484, I don't see that many in their bags now.

@Klikini I'll let you look into the achievement issues since you know that system better. My cursory glance does not suggest why there is a problem.

**Comment by Klikini** [comment] 2016-03-05 00:23
I replied, but apparently it's gone now.

I looked in the database and couldn't find `babi1`, but I found that `babi` had 0-1 uses for each of the items.

**Comment by babi1** [comment] 2016-03-05 07:52
My avatar name is the same as On Glitch : babi 
I am goingi now to do some harvesting again and I will open a report so you could see which is the matter.

**Comment by Klikini** [comment] 2016-05-09 23:25
https://github.com/ChildrenOfUr/coUserver/commit/12468aaf212ba38b1959a71ad0d232ada5949a49 should've fixed it (I tested it)

**Closed as completed** 2016-05-09 23:24 UTC
Labels: bug, server
