### ISSUE TITLE
Jal Non-existent map boundary

### ISSUE THREAD

**Issue by Mturtle7** [ChildrenOfUr/cou-issues#1188] opened 2016-07-07 19:37 UTC
My character seems to be able to swim above the visible mini-map boundary for all the Jal streets.
![screen shot 2016-07-07 at 12 27 50 pm](https://cloud.githubusercontent.com/assets/20344551/16667086/851905fa-443f-11e6-8acb-947e7a59c6f7.png)

**Comment by lizzard** [comment] 2016-07-08 18:31
Duplicate of issue 1187

**Closed as completed by lizzard** 2016-07-08 18:31 UTC
Labels: duplicate
