### ISSUE TITLE
Firefox won't connect to the server

### ISSUE THREAD

**Issue by diamondflamer** [ChildrenOfUr/cou-issues#54] opened 2015-09-20 14:37 UTC
Using up to date firefox on Win 10
 For the past few months every time I try and access the game it takes ages to load, then when I finally get in I am booted straight out with a "server down, please try again later" error message on a blackish screen over the game, then it tries to reload and goes into an endless cycle.

**Comment by Klikini** [comment] 2015-09-20 14:43
I just checked the server and it is currently up (with a player on), so could you please try in Chrome or Opera? We've had several cases where Firefox won't connect to the server port, but Chrome and Opera will. Thanks!

**Comment by diamondflamer** [comment] 2015-09-20 14:46
Yeah, I've got in via chrome fine, but laptop is too slow to run chrome and
firefox at the same time and an app I like to run in the background with
firefox is really poor in chrome so really don't want to have to use chrome
just so I can access this game. Really love how much things have progressed
since I last paid a visit though, can see myself spending more time here
over the coming months if the firefox issue is sorted.

**Comment by Klikini** [comment] 2015-09-20 14:50
The reason Firefox has issues is because of the way dart2js (the compiler) handles the web connectivity parts of the game with its own APIs (dart2js is very Google-influenced, so it works best with Google Chrome and Opera, which uses Google's code as a base).

So, while we'll *try* to work on the Firefox compatibility issues, it's not something we have a lot of control over.

**Comment by diamondflamer** [comment] 2015-09-20 14:51
That's a real shame :(, it may well be the decider between people being
able to play the game or not. Hopefully you can find a way around it.

**Comment by Klikini** [comment] 2015-09-20 15:30
Yeah, it's the same with window dragging. Firefox doesn't support figuring out where your mouse is when dragging the way Chrome and Opera do, so we can't support window dragging in FF currently.

**Comment by jdiwnab** [comment] 2015-11-01 01:37
I'd like to second this issue. Occasionally, I can get past the reload, but mostly I get stuck in a reload loop.

**Comment by Klikini** [comment] 2016-01-10 02:49
_Imported from #338:_

Firefox is not officially supported at the moment (http://childrenofur.com/about/#compatibility).

Most of the problems are caused by the fact that Dart compiles to JavaScript without input from us, and it uses web APIs that Firefox does not yet support.

While this is a severely limiting factor, we will try to work on Firefox support in the future.

**Comment by RobertBlackhart** [comment] 2016-01-21 02:57
This these issues seems to be resolved in the latest dev version.

**Closed by RobertBlackhart** 2016-01-21 02:57 UTC
Labels: project: client, type: bug
